name: Code Coverage

on:
  push:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ${{ github.branch }}
        uses: actions/checkout@v2

      - name: Grab Node version from NVMRC version
        run: echo "NVMRC=$(cat .nvmrc)" >> "${GITHUB_ENV}"

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NVMRC }}

      - name: Install packages
        run: npm ci

      - name: Test and collect coverage
        run: npm run coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: .
          name: github-action
          fail_ci_if_error: true
          verbose: true
